-- Cria pedidos genericos associados ao fluxo de atendimento.
CREATE TABLE IF NOT EXISTS pedidos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atendimento_id INTEGER NOT NULL REFERENCES atendimentos(id),
    empresa_id INTEGER NOT NULL,
    protocolo VARCHAR(50) NOT NULL UNIQUE,
    itens TEXT NOT NULL,
    total DOUBLE PRECISION NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'confirmado',
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pedidos_atendimento_id ON pedidos(atendimento_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_empresa_id ON pedidos(empresa_id);
